baseurl = "https://uzerp.com"
title = "uzERP Business Management Software"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
#disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "Case Studies"
    url  = "/studies/summary/"
    weight = 3

[[menu.main]]
    name = "Documentation"
    identifier = "doc"
    url  = "https://doc.uzerp.com"
    weight = 4

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/uzerpllp"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com/uzerp"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:info@uzerp.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "uzERP LLP"
    defaultKeywords = ["ERP", "business", "manufacturing", "financials"]
    defaultDescription = "uzERP – Open Source Business Management for the SME"

    # Google Maps API key (if not set will default to not passing a key.)
    #googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    #email = "your@email.com"

    about_us = "<p>uzERP is an Open Source modular business system designed for Small and Medium sized Enterprises (SME).</p>"
    copyright = "Copyright (c) 2019, uzERP LLP; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>uzERP LLP</strong>
        <br>Showground Road,
        <br>Severn Delta Building,
        <br>Bridgwater,
        <br>Somerset,
        <br>TA6 6AJ
        <br>
        <strong>Great Britain</strong>
      </p>
      """
    #latitude = "51.1098937"
    #longitude = "2.9921611"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on 07976 953 698 or info@uzerp.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.
    
[params.teaser]
    #enable = true
    link_url = "#"
    link_text = "Learn More"
    
[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-info"
    title = "Take uzERP for a spin"
    subtitle = "Take a closer look at uzERP via the online Demo - to log in use the following... Username: admin Password: admin"
    link_url = "https://demo.uzerp.com/"
    link_text = "Go to Demo"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Some of our Customers"
    #subtitle = "Some of the companies already getting the benefits from using uzERP to help run their business...."

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = ""

